# -*- coding: utf-8 -*-
"""Kashish Bajaj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_qGkC2tYCpFnTC00tvoSSN118CF4flq
"""

s={1, 2, 5, 8}
s.add(9)
s

#immutable:- immutable objects are those objects whose value can not be changed
# Example:- tupple, string

tup = (2,4,5,7,87,8)
print(tup[0])

# Discuss the types of different operators in python and provide examples of how they are used.
# Ans. 1.Arithmatic Operators:-
# Example:- +, -, *, /, %, **.
a=5
b=8
a+b

# 2. Comparison Operators:-
# Example:- <, >, >=, <=, ==, !=.
a=10
b=15
a>b

# 3. Logical Operators:-
# Example:-
# Logical and
# Logical or
# Logical not
a=15
b=20
(a>10)and(b<30)

a=50
b=60
(a>100)or(b<10)

# 4. Bitwise Operators:-
#Example:-
# Bitwise AND(&)
# Bitwise OR(|)
# Bitwise XOR(^)
# Bitwise left shift(<<)
# Bitwise right shift(>>)
a=12
b=5
a&b

a|b

a^b

a<<2

a>>2

#Q5 Explain typecasting in python with example.
# Ans. Type casting is the method to convert the python variable datatype into a certain data type.
str= "123"
result=int(str)
result
type(result)

int= 123
result= float(int)
result
type(result)

fl= 56.6
result= int(fl)
result
type(result)

tup= (1, 2, 3, 5)
result= list(tup)
result
type(result)

#Q6 How conditional statement work in python? illustrate with example.
# Ans. If the condition is true, the if block code is executed and if the condition is false, the else block code is executed.
# Types of conditional statement:-
# 1. if statement
# 2. if-else startElement
# 3. if-elif else startElement
# 4. nested if-else statement

#Example of if statement
age= 19
if age>=18:
    print("You are eligible for voting")

#Example of if-else statement
age=17
if age>=18:
    print("You are eligible for vote")
else:
    print("You are not eligible for vote")

#Example of if-elif else statement
grade= 5.5
if grade>=7.0 and grade<=10.0:
    print("First Division")
elif grade>=5.0 and grade<=7.0:
    print("Second Division")
else:
    print("Third Division")

#nested if-else statement
num = 5

if num > 0:
    print("The number is positive.")
else:
    if num < 0:
        print("The number is negative.")
    else:
        print("The number is zero.")

#Loop Statement:- LOOP statements execute a sequence of statements multiple times.
# Types of loop statement:-
# 1. For loop statement.
# 2. While loop statement.
for item in range(1, 5, 1):
    print("Hello i am jarvis")

i = 1
while i < 6:
    print(i)
    i += 1

#Break and Continue Statement:- Break statement stops the entire process of the loop and Continue statement only stops the current iteration of the loop.
# Example of break statement:-
for item in range(1,10,1):
    if item%2==0:
        break
    print(item)

# Example of continue statement:-
for item in range(1,10,1):
    if item%2==0:
        continue
    print(item)

